apiVersion: v1
kind: Service
metadata:
  name: blockchain101-frontend
  namespace: blockchain101
  labels:
    app: blockchain101-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: blockchain101-frontend
